<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLxYUzPU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLxYUzPU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLxYUzPU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLxYUzPU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLxYUzPU\App_KernelDevDebugContainer([
    'container.build_hash' => 'LxYUzPU',
    'container.build_id' => 'ec83c90d',
    'container.build_time' => 1708522286,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLxYUzPU');
